module.exports = {
  preset: "ts-jest",
  testEnvironment: "node",
  roots: ["<rootDir>/src"],
  testMatch: ["**/__tests__/**/*.ts", "**/?(*.)+(spec|test).ts"],
  transform: {
    "^.+\\.ts$": "ts-jest",
  },
  collectCoverageFrom: [
    "src/**/*.ts",
    "!src/**/*.d.ts",
    "!src/server.ts",
    "!src/__tests__/**",
    "!src/test-*.ts",
    "!src/**/*.test.ts",
    "!src/**/*.spec.ts",
  ],
  coverageDirectory: "coverage",
  coverageReporters: ["text", "lcov", "html"],
  coverageThreshold: {
    global: {
      branches: 60,
      functions: 65,
      lines: 70,
      statements: 70,
    },
  },
  setupFilesAfterEnv: ["<rootDir>/src/test-setup.ts"],
  testTimeout: 30000,
  verbose: true,
  detectOpenHandles: true,
  forceExit: true,
  maxWorkers: 4,
  testPathIgnorePatterns: ["/node_modules/", "/dist/", "/coverage/"],
  moduleFileExtensions: ["ts", "tsx", "js", "jsx", "json"],
  globalSetup: "<rootDir>/src/__tests__/setup/globalSetup.ts",
  globalTeardown: "<rootDir>/src/__tests__/setup/globalTeardown.ts",
};
